[@ww.textfield labelKey="projectName.label" name="projectName" descriptionKey="projectName.description" required='true'/]
[@ww.textfield labelKey="branchName.label" name="branchName" descriptionKey="branchName.description" required='true'/]
[@ww.textfield labelKey="viewerApi.label" name="viewerApi" descriptionKey="viewerApi.description" required='true'/]
[@ww.textfield labelKey="userName.label" name="userName" descriptionKey="userName.description" required='false'/]
[@ww.password labelKey="password.label" name="password" descriptionKey="password.description" required='false'/]