name: TICS Analyzer

on: [workflow_dispatch]
#  schedule:
#    - cron: "00 00 * * *"

jobs:
  TICSQServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - name: Setup Atlassian SDK
        uses: rodrigo-nogues/github-action-install-atlassian-sdk@v1
      - name: Build with Atlassian SDK
        run: atlas-package -Dversion
      - name: Install and run TICSQSERVER
        env:
          TICSAUTHTOKEN: ${{ secrets.EBOIT_ANALYZER_TOKEN }}
        run: |
          . <(curl --silent --show-error "https://eboit.tiobe.com/tiobeweb/TICS/api/public/v1/fapi/installtics/Script?cfg=main&platform=linux&url=https://eboit.tiobe.com/tiobeweb/TICS/")
          TICSQServer -project 'Bamboo' -branchdir .
